<?php

/**
 * @file
 * Contains wcc_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wcc_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wcc_migrate module.
    case 'help.page.wcc_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('WCC Migrate') . '</p>';
      return $output;

    default:
  }
}
